apiVersion: v1
kind: Service
metadata:
  name: kuber-service-lb
spec:
  externalTrafficPolicy: Local
  selector:
    app: nginx-ingress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer