apiVersion: v1
kind: Service
metadata:
  name: kuber-service-lb
spec:
  externalTrafficPolicy: Local
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.container.containerPort }}
  type: LoadBalancer